language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t albertojnk/scrapper-front-test -f ./frontend/Dockerfile ./frontend
    - docker build -t albertojnk/scrapper-back-test -f ./backend/Dockerfile ./backend

script:
    - docker run -e CI=true albertojnk/scrapper-front-test npm test -- --coverage

after_success:
    - docker build -t albertojnk/screapper-frontend ./frontend
    - docker build -t albertojnk/screapper-backend ./backend
    # login to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take images and push to dockerhub
    - docker push albertojnk/screapper-frontend
    - docker push albertojnk/screapper-backend
