version: '3'
services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile-backend
    networks: 
        - base_network
    ports:
      - "8000:8000"
    volumes: 
      - "./backend:/app"

  frontend:
    build:
        context: .
        dockerfile: Dockerfile-frontend
    networks: 
        - base_network
    ports:
      - "4200:4200"
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
      
networks:
    base_network: