version: '3'
services:
  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile.dev
    networks: 
        - base_network
    ports:
      - "8000:8000"
    volumes: 
      - "./backend:/app"

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile.dev
    networks: 
        - base_network
    ports:
      - "4200:4200"
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
      
networks:
    base_network: